"""
seed_loader.py — Populates the database with realistic demo pricing data
for common service categories so the Market Comparator works from day one.

Usage:
    python -m app.data.seed_loader

This is safe to run multiple times — it uses upsert logic and skips rows
that already exist. It should be run AFTER supabase db reset has seeded
the categories table (migration 012_seed.sql).
"""
import os
import random
import uuid
from datetime import datetime, timedelta, timezone

from app.data.db import get_client

# Pricing profiles keyed by category slug.
# Each tuple is (mean_price, std_dev) in USD/hr.
CATEGORY_PRICE_PROFILES: dict[str, tuple[float, float]] = {
    "web-development":   (90,  25),
    "graphic-design":    (55,  18),
    "photography":       (65,  20),
    "video-editing":     (60,  18),
    "tutoring":          (40,  12),
    "writing-editing":   (45,  14),
    "music-audio":       (55,  16),
    "landscaping":       (35,  10),
    "cleaning":          (30,   8),
    "moving-help":       (40,  10),
    "handyman-services": (45,  12),
    "data-entry":        (25,   7),
    "social-media":      (42,  13),
    "translation":       (48,  14),
    "event-planning":    (58,  17),
}

SAMPLES_PER_CATEGORY = 40  # transactions to generate per category
SEED_USER_COUNT = 20       # synthetic users to create


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _past(days: int) -> str:
    return (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()


def run_seed():
    client = get_client()

    print("Fetching categories…")
    cats = client.table("categories").select("id, slug").execute().data or []
    if not cats:
        raise RuntimeError(
            "No categories found. Run `supabase db reset` to apply migration 012_seed.sql first."
        )
    cat_map: dict[str, str] = {c["slug"]: c["id"] for c in cats}

    # We cannot create real auth.users rows from the service role via the REST API,
    # so we insert directly into the public.users table using pre-generated UUIDs.
    # In production, users sign up through Supabase Auth — this is demo data only.
    print(f"Seeding {SEED_USER_COUNT} synthetic users…")
    freelancer_ids: list[str] = []
    customer_ids:   list[str] = []

    for i in range(SEED_USER_COUNT):
        uid = str(uuid.uuid4())
        role = "freelancer" if i < SEED_USER_COUNT // 2 else "customer"
        row = {
            "id":    uid,
            "email": f"seed_user_{i}_{uid[:8]}@example.com",
            "role":  role,
        }
        # Insert ignoring conflicts (idempotent).
        client.table("users").upsert(row, on_conflict="id").execute()
        if role == "freelancer":
            freelancer_ids.append(uid)
        else:
            customer_ids.append(uid)

    print(f"  {len(freelancer_ids)} freelancers, {len(customer_ids)} customers created.")

    # Create one listing per freelancer per category (round-robin).
    print("Seeding listings…")
    listing_rows: list[dict] = []
    for fi, fid in enumerate(freelancer_ids):
        slug = list(CATEGORY_PRICE_PROFILES.keys())[fi % len(CATEGORY_PRICE_PROFILES)]
        cat_id = cat_map.get(slug)
        if not cat_id:
            continue
        listing_rows.append({
            "id":            str(uuid.uuid4()),
            "freelancer_id": fid,
            "category_id":   cat_id,
            "title":         f"Seed {slug.replace('-', ' ').title()} Service",
            "description":   f"Demo listing for {slug} — generated by seed_loader.",
            "is_active":     True,
        })

    if listing_rows:
        client.table("listings").upsert(listing_rows, on_conflict="id").execute()
    print(f"  {len(listing_rows)} listings created.")

    # Generate offers + transactions for each category.
    print("Seeding transactions…")
    tx_count = 0
    for slug, (mean, std) in CATEGORY_PRICE_PROFILES.items():
        cat_id = cat_map.get(slug)
        if not cat_id:
            print(f"  Skipping {slug} — not found in categories table.")
            continue

        # Find a listing in this category to attach offers to.
        listing_res = (
            client.table("listings")
            .select("id, freelancer_id")
            .eq("category_id", cat_id)
            .limit(1)
            .execute()
        )
        listing_rows_found = listing_res.data or []
        if not listing_rows_found:
            print(f"  Skipping {slug} — no listing found.")
            continue

        listing = listing_rows_found[0]

        for j in range(SAMPLES_PER_CATEGORY):
            price = max(10.0, round(random.gauss(mean, std), 2))
            days_ago = random.randint(1, 365)
            cid = customer_ids[j % len(customer_ids)]

            # Offer
            offer_id = str(uuid.uuid4())
            client.table("offers").upsert(
                {
                    "id":            offer_id,
                    "customer_id":   cid,
                    "freelancer_id": listing["freelancer_id"],
                    "listing_id":    listing["id"],
                    "amount":        price,
                    "status":        "active",
                    "created_at":    _past(days_ago + 1),
                },
                on_conflict="id",
            ).execute()

            # Transaction
            tx_id = str(uuid.uuid4())
            client.table("transactions").upsert(
                {
                    "id":            tx_id,
                    "offer_id":      offer_id,
                    "customer_id":   cid,
                    "freelancer_id": listing["freelancer_id"],
                    "listing_id":    listing["id"],
                    "category_id":   cat_id,
                    "final_price":   price,
                    "completed_at":  _past(days_ago),
                },
                on_conflict="id",
            ).execute()
            tx_count += 1

        print(f"  {slug}: {SAMPLES_PER_CATEGORY} transactions seeded.")

    print(f"\nSeed complete. {tx_count} total transactions inserted.")
    print("The Market Comparator pricing_report_aggregates view is now populated.")


if __name__ == "__main__":
    run_seed()